@startuml
hide empty members
skinparam classAttributeIconSize 0
skinparam linetype ortho
title main-java-com-conceptcoding-structuralpatterns-decorator
interface "com.conceptcoding.structuralpatterns.decorator.BasePizza" as com_conceptcoding_structuralpatterns_decorator_BasePizza {
  ~getDescription(): String
  ~getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.ChickenDominator" as com_conceptcoding_structuralpatterns_decorator_ChickenDominator {
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.ExtraCheeseTopping" as com_conceptcoding_structuralpatterns_decorator_ExtraCheeseTopping {
  +ExtraCheeseTopping(pizza: BasePizza)
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.Farmhouse" as com_conceptcoding_structuralpatterns_decorator_Farmhouse {
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.MushroomTopping" as com_conceptcoding_structuralpatterns_decorator_MushroomTopping {
  +MushroomTopping(pizza: BasePizza)
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.PepperoniTopping" as com_conceptcoding_structuralpatterns_decorator_PepperoniTopping {
  +PepperoniTopping(pizza: BasePizza)
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.PizzaShop" as com_conceptcoding_structuralpatterns_decorator_PizzaShop {
  +main(args: String[]): void {static}
}
class "com.conceptcoding.structuralpatterns.decorator.PlainPizza" as com_conceptcoding_structuralpatterns_decorator_PlainPizza {
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.TandooriPaneerDelight" as com_conceptcoding_structuralpatterns_decorator_TandooriPaneerDelight {
  +getDescription(): String
  +getCost(): double
}
class "com.conceptcoding.structuralpatterns.decorator.ToppingDecorator" as com_conceptcoding_structuralpatterns_decorator_ToppingDecorator {
  ~pizza: BasePizza
  --
  +ToppingDecorator(pizza: BasePizza)
}
class "com.conceptcoding.structuralpatterns.decorator.VeggiesTopping" as com_conceptcoding_structuralpatterns_decorator_VeggiesTopping {
  +VeggiesTopping(pizza: BasePizza)
  +getDescription(): String
  +getCost(): double
}
com_conceptcoding_structuralpatterns_decorator_BasePizza <|.. com_conceptcoding_structuralpatterns_decorator_ChickenDominator : implements
com_conceptcoding_structuralpatterns_decorator_BasePizza <|.. com_conceptcoding_structuralpatterns_decorator_Farmhouse : implements
com_conceptcoding_structuralpatterns_decorator_BasePizza <|.. com_conceptcoding_structuralpatterns_decorator_PlainPizza : implements
com_conceptcoding_structuralpatterns_decorator_BasePizza <|.. com_conceptcoding_structuralpatterns_decorator_TandooriPaneerDelight : implements
com_conceptcoding_structuralpatterns_decorator_BasePizza <|.. com_conceptcoding_structuralpatterns_decorator_ToppingDecorator : implements
com_conceptcoding_structuralpatterns_decorator_ToppingDecorator <|-- com_conceptcoding_structuralpatterns_decorator_ExtraCheeseTopping : is-a
com_conceptcoding_structuralpatterns_decorator_ToppingDecorator <|-- com_conceptcoding_structuralpatterns_decorator_MushroomTopping : is-a
com_conceptcoding_structuralpatterns_decorator_ToppingDecorator <|-- com_conceptcoding_structuralpatterns_decorator_PepperoniTopping : is-a
com_conceptcoding_structuralpatterns_decorator_ToppingDecorator <|-- com_conceptcoding_structuralpatterns_decorator_VeggiesTopping : is-a
com_conceptcoding_structuralpatterns_decorator_ToppingDecorator o-- com_conceptcoding_structuralpatterns_decorator_BasePizza : has-a (pizza)
@enduml
